baseURL: https://rodolfoviana.com.br
languageCode: pt-br
defaultContentLanguage: pt
title: Rodolfo Viana
theme: 
googleAnalytics: 
disqusShortname: 
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Publicações e projetos relacionados a ciência de dados
  homeMetaContent: Publicações e projetos relacionados a ciência de dados
  footer: 2023 &copy; Rodolfo Viana. Feito com [Hugo](https://gohugo.io/), [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)
  dateFormat: Jan 2, 2006
  codePenUser: 
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Rodolfo Viana
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  utterances:
    repo: username/username.github.io
    issueTerm: title
    theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
