baseURL: https://rodolfoviana.com.br
languageCode: pt-br
defaultContentLanguage: pt
title: Rodolfo Viana
theme: 
googleAnalytics: 
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Publicações e projetos relacionados a ciência de dados
  homeMetaContent: Publicações e projetos relacionados a ciência de dados
  dateFormat: Jan 2, 2006
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false

  logoAlt: Rodolfo Viana
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    #- name: Publicações
    #  url: /publicacoes/
    #  weight: 1
    - name: Projetos
      url: /projetos/
      weight: 2
    - name: RSS
      url: /index.xml
      weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
